// <auto-generated />
using System;
using GtdSystem.BackService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GtdSystem.BackService.Migrations
{
    [DbContext(typeof(UserTaskContext))]
    [Migration("20190325132253_usertask")]
    partial class usertask
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GtdSystem.BackService.Models.Context", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Context");
                });

            modelBuilder.Entity("GtdSystem.BackService.Models.Subtask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("Done");

                    b.Property<int?>("UserTaskId");

                    b.HasKey("Id");

                    b.HasIndex("UserTaskId");

                    b.ToTable("Subtask");
                });

            modelBuilder.Entity("GtdSystem.BackService.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<bool>("Done");

                    b.Property<int>("NecessaryTime");

                    b.Property<int>("Priority");

                    b.Property<DateTime>("StartDate");

                    b.Property<int?>("TaskContextId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TaskContextId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("GtdSystem.BackService.Models.Subtask", b =>
                {
                    b.HasOne("GtdSystem.BackService.Models.UserTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("UserTaskId");
                });

            modelBuilder.Entity("GtdSystem.BackService.Models.UserTask", b =>
                {
                    b.HasOne("GtdSystem.BackService.Models.Context", "TaskContext")
                        .WithMany()
                        .HasForeignKey("TaskContextId");
                });
#pragma warning restore 612, 618
        }
    }
}
